version: 2.1

orbs:
  node: circleci/node@1.1.4

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: npm
          filters:
            branches:
              ignore:
                - main
      - build:
          context: npm
          publish: true
          filters:
            branches:
              only:
                - main

jobs:
  build:
    parameters:
      publish:
        type: boolean
        default: false
    docker:
      - image: circleci/node:erbium
    working_directory: ~/project
    steps:
      - checkout
      - run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc'
      - run: npm ci
      - run: npm run build
      - when:
          condition: <<parameters.publish>>
          steps:
            - run: ./bump.sh package.json
            - run: npm publish
