import { newDate } from "./testData";

import * as GraphQLAutoGeneratedType from "./graphql-types-only";

export interface AuthorOptions {
  __typename?: "Author";
  id?: GraphQLAutoGeneratedType.Author["id"];
  name?: GraphQLAutoGeneratedType.Author["name"];
  summary?: AuthorSummaryOptions;
  popularity?: PopularityDetailOptions | GraphQLAutoGeneratedType.Popularity;
  workingDetail?: WorkingDetailOptions | GraphQLAutoGeneratedType.Working;
  working?: GraphQLAutoGeneratedType.Author["working"];
  birthday?: GraphQLAutoGeneratedType.Author["birthday"];
  books?: Array<BookOptions>;
}

export function newAuthor(
  options: AuthorOptions = {},
  cache: Record<string, any> = {},
): GraphQLAutoGeneratedType.Author {
  const o = (cache["Author"] = {} as GraphQLAutoGeneratedType.Author);
  o.__typename = "Author";
  o.id = options.id ?? nextFactoryId("Author");
  o.name = options.name ?? "name";
  o.summary = maybeNewAuthorSummary(options.summary, cache, options.hasOwnProperty("summary"));
  o.popularity = enumOrDetailOfPopularity(options.popularity);
  o.workingDetail = enumOrDetailOfWorking(options.workingDetail);
  o.working = options.working ?? null;
  o.birthday = options.birthday ?? null;
  o.books = (options.books ?? []).map((i) => maybeNewBook(i, cache, options.hasOwnProperty("books")));
  return o;
}

function maybeNewAuthor(
  value: AuthorOptions | undefined,
  cache: Record<string, any>,
  isSet: boolean = false,
): GraphQLAutoGeneratedType.Author {
  if (value === undefined) {
    return isSet ? undefined : cache["Author"] || newAuthor({}, cache);
  } else if (value.__typename) {
    return value as GraphQLAutoGeneratedType.Author;
  } else {
    return newAuthor(value, cache);
  }
}

function maybeNewOrNullAuthor(
  value: AuthorOptions | undefined | null,
  cache: Record<string, any>,
): GraphQLAutoGeneratedType.Author | null {
  if (!value) {
    return null;
  } else if (value.__typename) {
    return value as GraphQLAutoGeneratedType.Author;
  } else {
    return newAuthor(value, cache);
  }
}
export interface AuthorSummaryOptions {
  __typename?: "AuthorSummary";
  id?: GraphQLAutoGeneratedType.AuthorSummary["id"];
  author?: AuthorOptions;
  numberOfBooks?: GraphQLAutoGeneratedType.AuthorSummary["numberOfBooks"];
  amountOfSales?: GraphQLAutoGeneratedType.AuthorSummary["amountOfSales"];
}

export function newAuthorSummary(
  options: AuthorSummaryOptions = {},
  cache: Record<string, any> = {},
): GraphQLAutoGeneratedType.AuthorSummary {
  const o = (cache["AuthorSummary"] = {} as GraphQLAutoGeneratedType.AuthorSummary);
  o.__typename = "AuthorSummary";
  o.id = options.id ?? nextFactoryId("AuthorSummary");
  o.author = maybeNewAuthor(options.author, cache, options.hasOwnProperty("author"));
  o.numberOfBooks = options.numberOfBooks ?? 0;
  o.amountOfSales = options.amountOfSales ?? null;
  return o;
}

function maybeNewAuthorSummary(
  value: AuthorSummaryOptions | undefined,
  cache: Record<string, any>,
  isSet: boolean = false,
): GraphQLAutoGeneratedType.AuthorSummary {
  if (value === undefined) {
    return isSet ? undefined : cache["AuthorSummary"] || newAuthorSummary({}, cache);
  } else if (value.__typename) {
    return value as GraphQLAutoGeneratedType.AuthorSummary;
  } else {
    return newAuthorSummary(value, cache);
  }
}

function maybeNewOrNullAuthorSummary(
  value: AuthorSummaryOptions | undefined | null,
  cache: Record<string, any>,
): GraphQLAutoGeneratedType.AuthorSummary | null {
  if (!value) {
    return null;
  } else if (value.__typename) {
    return value as GraphQLAutoGeneratedType.AuthorSummary;
  } else {
    return newAuthorSummary(value, cache);
  }
}
export interface BookOptions {
  __typename?: "Book";
  name?: GraphQLAutoGeneratedType.Book["name"];
  popularity?: PopularityDetailOptions | GraphQLAutoGeneratedType.Popularity | null;
  coauthor?: AuthorOptions | null;
  reviews?: Array<BookReviewOptions | null> | null;
}

export function newBook(options: BookOptions = {}, cache: Record<string, any> = {}): GraphQLAutoGeneratedType.Book {
  const o = (cache["Book"] = {} as GraphQLAutoGeneratedType.Book);
  o.__typename = "Book";
  o.name = options.name ?? "name";
  o.popularity = enumOrDetailOrNullOfPopularity(options.popularity);
  o.coauthor = maybeNewOrNullAuthor(options.coauthor, cache);
  o.reviews = (options.reviews ?? []).map((i) => maybeNewOrNullBookReview(i, cache));
  return o;
}

function maybeNewBook(
  value: BookOptions | undefined,
  cache: Record<string, any>,
  isSet: boolean = false,
): GraphQLAutoGeneratedType.Book {
  if (value === undefined) {
    return isSet ? undefined : cache["Book"] || newBook({}, cache);
  } else if (value.__typename) {
    return value as GraphQLAutoGeneratedType.Book;
  } else {
    return newBook(value, cache);
  }
}

function maybeNewOrNullBook(
  value: BookOptions | undefined | null,
  cache: Record<string, any>,
): GraphQLAutoGeneratedType.Book | null {
  if (!value) {
    return null;
  } else if (value.__typename) {
    return value as GraphQLAutoGeneratedType.Book;
  } else {
    return newBook(value, cache);
  }
}
export interface BookReviewOptions {
  __typename?: "BookReview";
  rating?: GraphQLAutoGeneratedType.BookReview["rating"];
}

export function newBookReview(
  options: BookReviewOptions = {},
  cache: Record<string, any> = {},
): GraphQLAutoGeneratedType.BookReview {
  const o = (cache["BookReview"] = {} as GraphQLAutoGeneratedType.BookReview);
  o.__typename = "BookReview";
  o.rating = options.rating ?? 0;
  return o;
}

function maybeNewBookReview(
  value: BookReviewOptions | undefined,
  cache: Record<string, any>,
  isSet: boolean = false,
): GraphQLAutoGeneratedType.BookReview {
  if (value === undefined) {
    return isSet ? undefined : cache["BookReview"] || newBookReview({}, cache);
  } else if (value.__typename) {
    return value as GraphQLAutoGeneratedType.BookReview;
  } else {
    return newBookReview(value, cache);
  }
}

function maybeNewOrNullBookReview(
  value: BookReviewOptions | undefined | null,
  cache: Record<string, any>,
): GraphQLAutoGeneratedType.BookReview | null {
  if (!value) {
    return null;
  } else if (value.__typename) {
    return value as GraphQLAutoGeneratedType.BookReview;
  } else {
    return newBookReview(value, cache);
  }
}
export interface CalendarIntervalOptions {
  __typename?: "CalendarInterval";
  start?: GraphQLAutoGeneratedType.CalendarInterval["start"];
  end?: GraphQLAutoGeneratedType.CalendarInterval["end"];
}

export function newCalendarInterval(
  options: CalendarIntervalOptions = {},
  cache: Record<string, any> = {},
): GraphQLAutoGeneratedType.CalendarInterval {
  const o = (cache["CalendarInterval"] = {} as GraphQLAutoGeneratedType.CalendarInterval);
  o.__typename = "CalendarInterval";
  o.start = options.start ?? newDate();
  o.end = options.end ?? newDate();
  return o;
}

function maybeNewCalendarInterval(
  value: CalendarIntervalOptions | undefined,
  cache: Record<string, any>,
  isSet: boolean = false,
): GraphQLAutoGeneratedType.CalendarInterval {
  if (value === undefined) {
    return isSet ? undefined : cache["CalendarInterval"] || newCalendarInterval({}, cache);
  } else if (value.__typename) {
    return value as GraphQLAutoGeneratedType.CalendarInterval;
  } else {
    return newCalendarInterval(value, cache);
  }
}

function maybeNewOrNullCalendarInterval(
  value: CalendarIntervalOptions | undefined | null,
  cache: Record<string, any>,
): GraphQLAutoGeneratedType.CalendarInterval | null {
  if (!value) {
    return null;
  } else if (value.__typename) {
    return value as GraphQLAutoGeneratedType.CalendarInterval;
  } else {
    return newCalendarInterval(value, cache);
  }
}
export interface ChildOptions {
  __typename?: "Child";
  parent?: GraphQLAutoGeneratedType.Child["parent"];
}

export function newChild(options: ChildOptions = {}, cache: Record<string, any> = {}): GraphQLAutoGeneratedType.Child {
  const o = (cache["Child"] = {} as GraphQLAutoGeneratedType.Child);
  o.__typename = "Child";
  o.parent = maybeNewAuthor(options.parent, cache, options.hasOwnProperty("parent"));
  return o;
}

function maybeNewChild(
  value: ChildOptions | undefined,
  cache: Record<string, any>,
  isSet: boolean = false,
): GraphQLAutoGeneratedType.Child {
  if (value === undefined) {
    return isSet ? undefined : cache["Child"] || newChild({}, cache);
  } else if (value.__typename) {
    return value as GraphQLAutoGeneratedType.Child;
  } else {
    return newChild(value, cache);
  }
}

function maybeNewOrNullChild(
  value: ChildOptions | undefined | null,
  cache: Record<string, any>,
): GraphQLAutoGeneratedType.Child | null {
  if (!value) {
    return null;
  } else if (value.__typename) {
    return value as GraphQLAutoGeneratedType.Child;
  } else {
    return newChild(value, cache);
  }
}
export interface PopularityDetailOptions {
  __typename?: "PopularityDetail";
  code?: GraphQLAutoGeneratedType.PopularityDetail["code"];
  name?: GraphQLAutoGeneratedType.PopularityDetail["name"];
}

export function newPopularityDetail(
  options: PopularityDetailOptions = {},
  cache: Record<string, any> = {},
): GraphQLAutoGeneratedType.PopularityDetail {
  const o = (cache["PopularityDetail"] = {} as GraphQLAutoGeneratedType.PopularityDetail);
  o.__typename = "PopularityDetail";
  o.code = options.code ?? GraphQLAutoGeneratedType.Popularity.Low;
  o.name = options.name ?? "Low";
  return o;
}
export interface SaveAuthorResultOptions {
  __typename?: "SaveAuthorResult";
  author?: AuthorOptions;
}

export function newSaveAuthorResult(
  options: SaveAuthorResultOptions = {},
  cache: Record<string, any> = {},
): GraphQLAutoGeneratedType.SaveAuthorResult {
  const o = (cache["SaveAuthorResult"] = {} as GraphQLAutoGeneratedType.SaveAuthorResult);
  o.__typename = "SaveAuthorResult";
  o.author = maybeNewAuthor(options.author, cache, options.hasOwnProperty("author"));
  return o;
}

function maybeNewSaveAuthorResult(
  value: SaveAuthorResultOptions | undefined,
  cache: Record<string, any>,
  isSet: boolean = false,
): GraphQLAutoGeneratedType.SaveAuthorResult {
  if (value === undefined) {
    return isSet ? undefined : cache["SaveAuthorResult"] || newSaveAuthorResult({}, cache);
  } else if (value.__typename) {
    return value as GraphQLAutoGeneratedType.SaveAuthorResult;
  } else {
    return newSaveAuthorResult(value, cache);
  }
}

function maybeNewOrNullSaveAuthorResult(
  value: SaveAuthorResultOptions | undefined | null,
  cache: Record<string, any>,
): GraphQLAutoGeneratedType.SaveAuthorResult | null {
  if (!value) {
    return null;
  } else if (value.__typename) {
    return value as GraphQLAutoGeneratedType.SaveAuthorResult;
  } else {
    return newSaveAuthorResult(value, cache);
  }
}
export interface WorkingDetailOptions {
  __typename?: "WorkingDetail";
  code?: GraphQLAutoGeneratedType.WorkingDetail["code"];
  name?: GraphQLAutoGeneratedType.WorkingDetail["name"];
  extraField?: GraphQLAutoGeneratedType.WorkingDetail["extraField"];
}

export function newWorkingDetail(
  options: WorkingDetailOptions = {},
  cache: Record<string, any> = {},
): GraphQLAutoGeneratedType.WorkingDetail {
  const o = (cache["WorkingDetail"] = {} as GraphQLAutoGeneratedType.WorkingDetail);
  o.__typename = "WorkingDetail";
  o.code = options.code ?? GraphQLAutoGeneratedType.Working.Yes;
  o.name = options.name ?? "Yes";
  o.extraField = options.extraField ?? 0;
  return o;
}
export type NamedOptions = AuthorOptions | BookOptions | PopularityDetailOptions;

export type NamedType =
  | GraphQLAutoGeneratedType.Author
  | GraphQLAutoGeneratedType.Book
  | GraphQLAutoGeneratedType.PopularityDetail;

export type NamedTypeName = "Author" | "Book" | "PopularityDetail";

function maybeNewNamed(value: NamedOptions | undefined, cache: Record<string, any>): NamedType {
  if (value === undefined) {
    return cache["Author"] || newAuthor({}, cache);
  } else if (value.__typename) {
    return value as NamedType;
  } else {
    return newAuthor(value as unknown as AuthorOptions, cache);
  }
}

function maybeNewOrNullNamed(
  value: NamedOptions | undefined | null,
  cache: Record<string, any>,
): GraphQLAutoGeneratedType.Named | null {
  if (!value) {
    return null;
  } else if (value.__typename) {
    return value as NamedType;
  } else {
    return newAuthor(value as unknown as AuthorOptions, cache);
  }
}

const enumDetailNameOfPopularity = {
  Low: "Low",
  High: "High",
};

function enumOrDetailOfPopularity(
  enumOrDetail: PopularityDetailOptions | GraphQLAutoGeneratedType.Popularity | undefined,
): GraphQLAutoGeneratedType.PopularityDetail {
  if (enumOrDetail === undefined) {
    return newPopularityDetail();
  } else if (typeof enumOrDetail === "object" && "code" in enumOrDetail) {
    return {
      __typename: "PopularityDetail",
      code: enumOrDetail.code!,
      name: enumDetailNameOfPopularity[enumOrDetail.code!],
      ...enumOrDetail,
    } as GraphQLAutoGeneratedType.PopularityDetail;
  } else {
    return newPopularityDetail({
      code: enumOrDetail as GraphQLAutoGeneratedType.Popularity,
      name: enumDetailNameOfPopularity[enumOrDetail as GraphQLAutoGeneratedType.Popularity],
    });
  }
}

function enumOrDetailOrNullOfPopularity(
  enumOrDetail: PopularityDetailOptions | GraphQLAutoGeneratedType.Popularity | undefined | null,
): GraphQLAutoGeneratedType.PopularityDetail | null {
  if (enumOrDetail === null) {
    return null;
  }
  return enumOrDetailOfPopularity(enumOrDetail);
}

const enumDetailNameOfWorking = {
  YES: "Yes",
  NO: "No",
};

function enumOrDetailOfWorking(
  enumOrDetail: WorkingDetailOptions | GraphQLAutoGeneratedType.Working | undefined,
): GraphQLAutoGeneratedType.WorkingDetail {
  if (enumOrDetail === undefined) {
    return newWorkingDetail();
  } else if (typeof enumOrDetail === "object" && "code" in enumOrDetail) {
    return {
      __typename: "WorkingDetail",
      code: enumOrDetail.code!,
      name: enumDetailNameOfWorking[enumOrDetail.code!],
      ...enumOrDetail,
    } as GraphQLAutoGeneratedType.WorkingDetail;
  } else {
    return newWorkingDetail({
      code: enumOrDetail as GraphQLAutoGeneratedType.Working,
      name: enumDetailNameOfWorking[enumOrDetail as GraphQLAutoGeneratedType.Working],
    });
  }
}

function enumOrDetailOrNullOfWorking(
  enumOrDetail: WorkingDetailOptions | GraphQLAutoGeneratedType.Working | undefined | null,
): GraphQLAutoGeneratedType.WorkingDetail | null {
  if (enumOrDetail === null) {
    return null;
  }
  return enumOrDetailOfWorking(enumOrDetail);
}

const taggedIds: Record<string, string> = { AuthorSummary: "summary" };
let nextFactoryIds: Record<string, number> = {};

export function resetFactoryIds() {
  nextFactoryIds = {};
}

function nextFactoryId(objectName: string): string {
  const nextId = nextFactoryIds[objectName] || 1;
  nextFactoryIds[objectName] = nextId + 1;
  const tag = taggedIds[objectName] ?? objectName.replace(/[a-z]/g, "").toLowerCase();
  return tag + ":" + nextId;
}
